# -*- coding: utf-8 -*-
"""image_augmentation.ipynb의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yue2svBJ3u2s1tFnvN5blBSRF3PS1ZAQ
"""

os.getcwd()

# 구글 드라이브 연동
from google.colab import drive
drive.mount('/content/drive')
# 구글 드라이브를 colab 디렉토리 /content/drive 하위에 붙인다.
# 이 쉘을 실행하면 token 요청이 나오며, 연동 승인 후 token을 붙여 넣기 한다.

from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
# keras의 이미지 뻥튀기, 즉 image augmentation

datagen = ImageDataGenerator(
        rotation_range=40,
        width_shift_range=0.2,
        height_shift_range=0.2,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True,
        fill_mode='nearest')

img = load_img('/content/drive/MyDrive/crosswalk/cw42.jpg')  # this is a PIL image
# 구글 드라이브의 이미지 파일을 지정한다.

x = img_to_array(img)  # this is a Numpy array with shape (3, 150, 150)
x = x.reshape((1,) + x.shape)  # this is a Numpy array with shape (1, 3, 150, 150)

# the .flow() command below generates batches of randomly transformed images
# and saves the results to the `preview/` directory
i = 0
for batch in datagen.flow(x, batch_size=1,
                          save_to_dir='/content/drive/MyDrive/crosswalk/preview', save_prefix='cw', save_format='jpg'):
                          #저장되는 하위 폴더와 파일 형식을 정해준다.
    i += 1
    if i > 100: #이미지 수량
        break

